### Importing libraries

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Importing data

In [8]:
dataset = pd.read_csv("data_1.csv")
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [10]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [11]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


### Taking care of missing data
1. Ignore the records
2. Replace numeric values with average, median, mode


In [13]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [16]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


### Encoding categorical data
Creating binary vectors for categorical variables to avoid numerical oders

In [21]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [22]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [25]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [26]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


### Train test split

In [30]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

### Feature scaling

In [36]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:,3:] = sc.fit_transform(x_train[:,3:])
x_test[:,3:]= sc.transform(x_test[:,3:])

In [37]:
print(x_train)

[[0.0 1.0 0.0 1.4215361505506656 1.5284216894073757]
 [0.0 0.0 1.0 -1.6198900320228515 -1.6131954862097426]
 [0.0 1.0 0.0 0.09917694073609291 -0.19697441021726353]
 [1.0 0.0 0.0 1.1570643085877512 1.1693797264797052]
 [0.0 1.0 0.0 -1.2231822690784797 -1.0746325418182365]
 [1.0 0.0 0.0 -0.2975308222082789 0.09225383769669313]
 [0.0 0.0 1.0 -0.1652949012268216 -0.4463091066948129]
 [1.0 0.0 0.0 0.6281206246619221 0.5410562913562815]]


In [38]:
print(x_test)

[[1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]]
